title: Jie Li
tagline: Welcome to the dream land of J!
description: This is 洁宝
theme: jekyll-theme-tao

author:
  name: Jie Li
  url: https://github.com/jlli6t/jlli6t.github.io

plugins:
  - jekyll-paginate

paginate: 3

catalogue_path: /catalogue/
tags_path: /tags/
years_path: /years/
