title: Jie Li (She/Her/Hers)
tagline: A PhD student interested in microbial ecology
description: Passion is the only thing that can get you through the long years


author:
  name: Jie Li
  url: "https://twitter.com/jlli6t"
url: "htpps://jlli6t.github.io"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

paginate: 10

categories_path: /categories/
tags_path: /tags/
years_path: /years/

# manually added:
# use theme settings or not
ignore_theme_config: false

# Where things are
source              : .
destination         : ./_site
layouts_dir         : _layouts
data_dir            : _data
includes_dir        : _includes

# Handling Reading
safe                : false
include             : [".htaccess"]

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - _sass
  - README.md

# Serving
port                : 3080

# Outputting
permalink           : date
paginate_path       : /page:num
timezone            : null
