title: Jie Li
tagline: Welcome to my personel website.
description: This is a personel website of Jie.
theme: jekyll-theme-tao

author:
  name: Jie Li
  url: https://github.com/jlli6t/jlli6t.github.io

plugins:
  - jekyll-paginate

paginate: 2

categories_path: /categories/
tags_path: /tags/
