title: Jie Li (She/Her/Hers)
tagline: "PhD student interested in microbial ecology, bioinformatics and statistics"
description: Passion is the only thing that can get you through the long years|唯有热爱，可抵岁月漫长
theme: jekyll-theme-tao

author:
  name: Jie Li
  url: "htpps://jlli6t.github.io"


# Plugins
whitelist           : []
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

paginate: 10

categories_path: /categories/
tags_path: /tags/
years_path: /years/
cv_path: /cv/
home_path: /home/

# manually added:
# use theme settings or not
ignore_theme_config: false

# Where things are
source              : .
destination         : ./_site
layouts_dir         : _layouts
data_dir            : _data
includes_dir        : _includes
sass:
  sass_dir: _sass
collections:
  posts:
    output          : true

# Handling Reading
safe                : false
include             : [".htaccess"]

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - _sass
  - README.md

keep_files:
  - .git
  - .svn

markdown_ext        : "markdown,mkdown,mkdn,mkd,md"
strict_front_matter : false



# Conversion
markdown            : kramdown
highlighter         : rouge
lsi                 : false
excerpt_separator   : "\n\n"
incremental         : false

# Serving
port                : 3080

# Outputting
permalink           : date
paginate_path       : /page:num
timezone            : null

liquid:
  error_mode        : warn
  strict_filters    : false
  strict_variables  : false

# Markdown Processors
kramdown:
  auto_ids          : true
  entity_output     : as_char
  toc_levels        : [1, 2, 3, 4, 5, 6]
  smart_quotes      : lsquo,rsquo,ldquo,rdquo
  input             : GFM
  hard_wrap         : false
  footnote_nr       : 1
  show_warnings     : false
