title: Jie Li (She/Her)
tagline: "microbial ecology, bioinformatics, statistics"
description: This is the dream land of Jie, you are warmly welcomed.
theme: jekyll-theme-tao

author:
  name: Jie Li
  url: https://github.com/jlli6t/jlli6t.github.io

plugins:
  - jekyll-paginate

paginate: 3

categories_path: /categories/
tags_path: /tags/
years_path: /years/
